#!/bin/csh -f
################################################################################
# simulation top script
# change modelsim in this file dir and run "do this_file.do"
# project dir ---+---> hdl source dir
#                +---> sim script dir
#
################################################################################

# check if current dir has modelsim config file
set has_config  [file exists modelsim.do]
# config modelsim 
if {$has_config==1} { do modelsim.do  ; }

echo "+====================================="
echo "| Creat Lib Work soc                  "
echo "+====================================="
vlib work
vmap work work 

echo "+====================================="
echo "| Complile RTL Code of soc            "
echo "+====================================="
vlog -f ../filelist/filelist.f  

echo "+====================================="
echo "| Compiler Pass                       "
echo "| Being to Run Simulation             "
echo "+====================================="
vsim work.quad_core_tb -t 1ns

###################################### mus  ####################################
add wave -noupdate -format logic -color green   -radix hexadecimal quad_core_tb/u_quad_core/clk     
add wave -noupdate -format logic -color blue    -radix hexadecimal quad_core_tb/u_quad_core/rst     
add wave -noupdate -format logic -color yellow  -radix hexadecimal quad_core_tb/u_quad_core/en     
add wave -noupdate -format logic -color purple  -radix hexadecimal quad_core_tb/u_quad_core/a0     
add wave -noupdate -format logic -color purple  -radix hexadecimal quad_core_tb/u_quad_core/b0     
add wave -noupdate -format logic -color purple  -radix hexadecimal quad_core_tb/u_quad_core/c0     
add wave -noupdate -format logic -color purple  -radix hexadecimal quad_core_tb/u_quad_core/d0   
add wave -noupdate -format logic -color purple  -radix hexadecimal quad_core_tb/u_quad_core/g0     
add wave -noupdate -format logic -color green   -radix hexadecimal quad_core_tb/u_quad_core/a1     
add wave -noupdate -format logic -color green   -radix hexadecimal quad_core_tb/u_quad_core/b1     
add wave -noupdate -format logic -color green   -radix hexadecimal quad_core_tb/u_quad_core/c1     
add wave -noupdate -format logic -color green   -radix hexadecimal quad_core_tb/u_quad_core/d1     
add wave -noupdate -format logic -color green   -radix hexadecimal quad_core_tb/u_quad_core/g1     

add wave -noupdate -format logic -color purple  -radix hexadecimal quad_core_tb/u_quad_core/a2     
add wave -noupdate -format logic -color purple  -radix hexadecimal quad_core_tb/u_quad_core/b2     
add wave -noupdate -format logic -color purple  -radix hexadecimal quad_core_tb/u_quad_core/c2     
add wave -noupdate -format logic -color purple  -radix hexadecimal quad_core_tb/u_quad_core/d2   
add wave -noupdate -format logic -color purple  -radix hexadecimal quad_core_tb/u_quad_core/g2     
add wave -noupdate -format logic -color green   -radix hexadecimal quad_core_tb/u_quad_core/a3     
add wave -noupdate -format logic -color green   -radix hexadecimal quad_core_tb/u_quad_core/b3     
add wave -noupdate -format logic -color green   -radix hexadecimal quad_core_tb/u_quad_core/c3     
add wave -noupdate -format logic -color green   -radix hexadecimal quad_core_tb/u_quad_core/d3     
add wave -noupdate -format logic -color green   -radix hexadecimal quad_core_tb/u_quad_core/g3     


run 5us
