../dut/FP_adder_13ccs.v
../dut/FP_multiplier_10ccs.v
../dut/FP_subtractor_13ccs.v
../dut/binary_lib.v
../dut/FP_datapath.v
../dut/timing_ctl.v
../dut/shift13_register.v
../dut/shift23_register.v
../dut/fpu.v
../dut/fppu.v
../dut/quad_core.v
../tb/quad_core_tb.v
